### ISSUE TITLE
Cannot upgrade to version 0.12.3~ynh1

### ISSUE THREAD

**Issue by SiM** [mbugeia/gogs_ynh#52]
### Describe the bug

When upgrading gogs from `0.11.66~ynh2` to `0.12.3~ynh1`, the upgrade fails at step `Setting up source files`

### Context

- Hardware: *VPS*
- YunoHost version: 4.3.4.2
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: *using: `0.11.66~ynh2` - trying to upgrade to: `0.12.3~ynh1`

### Steps to reproduce
`yunohost app upgrade gogs`

### Logs
https://paste.yunohost.org/raw/inulikohit

The error seems to be here:
```
2021-12-20 12:37:52,725: DEBUG - + rm -rf /var/cache/yunohost/files_to_keep_during_setup_source/
2021-12-20 12:37:52,726: DEBUG - + '[' -n '/custom/conf/app.ini /custom/conf/auth.d/ldap.conf' ']'
2021-12-20 12:37:52,726: DEBUG - + '[' -e '' ']'
2021-12-20 12:37:52,726: DEBUG - + mkdir --parents ''
2021-12-20 12:37:52,727: WARNING - mkdir: impossible de créer le répertoire «  »: Aucun fichier ou dossier de ce type
```

**Comment by ghost** [comment]
Hello,
I have the same error.

**Context**
* hardware : Lenovo ThinkCenter M93, self hosted
* YunoHost version: 4.3.4.2
* I have access to my server: Through SSH | through the webadmin
* Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
* Using, or trying to install package version/branch: *using: 0.11.66~ynh2 - trying to upgrade to: 0.12.3~ynh1

**Steps to reproduce**

`yunohost app upgrade gogs`

**Logs**
https://paste.yunohost.org/raw/sisojadodu

**Comment by bachy** [comment]
+1 

https://paste.yunohost.org/raw/wozozazasa

**Comment by ericgaspar** [comment]
Sorry for the inconvenience.

I didn't realize that Gogs were still in use after its development has migrated to Gitea. The app is labeled as non maintained for a little bit more the 3 years.
gogs_ynh has been totally re-written without giving much thought to the legacy code. The script was old and almost everything has changed from path to variables naming and helpers to catch-up with new standards...

You can try to upgrade Gogs to the newer version with this branch 
`sudo yunohost app upgrade gogs -u https://github.com/YunoHost-Apps/gogs_ynh/tree/0.11.79-0.12.3`

**Comment by ghost** [comment]
Hello,

Thanks @ericgaspar .
